# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/tti
    REF boost-1.65.0
    SHA512 0d35a6291d3abb8ee29be59ea35dba9019d25ea737830d5e26306e012c9a1f7124f13531e15ccb21ac395375b4791ab25f5f938c5bea3a94fb92ef0c5b76c72f
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
