# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/phoenix
    REF boost-1.65.0
    SHA512 00356dc90424847e986da5df30afa1c86e15da67444de47ae949f93c95dd14cd664cda887c51bbc2a4d1856b43ea4406d82e37b5861cbe29a66530517a12c980
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
