# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/type_traits
    REF boost-1.65.0
    SHA512 33ebfdf37a8fb0bf4f1b8a3d9bcaabf58b1cd6b14827a5c0cd957ea9eb51b217c843c8cd14383fa77099c85e80523d8885ec61ec5c845a14e03f99fe3be64d48
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
