# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/align
    REF boost-1.65.0
    SHA512 a5185336c24f4e0ee03931a59490152cef1c55ec9d936326263b39d233922a1b29da79078a0174fa7dff8a2a6f611cb2d631895c6d8576c3ec2178a3b76cb146
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
