# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/tuple
    REF boost-1.65.0
    SHA512 d6d9a493ffc07586e0b44856cd76e5f304a0d3dff8d22ddfca4a29fab509bccfa08f1a363159a57540ee1b640ef69699a19b726db65440ecdbb38448f8a1f7d6
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
