# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/odeint
    REF boost-1.65.0
    SHA512 54c57c6626b3e8913497f30fb22eda615c00422573208b1438038b67c165ec1d3342b948b5a6848b92d612d66c3811e122b80f05f5df7187ceb3f3a672692e90
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
