# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/compatibility
    REF boost-1.65.0
    SHA512 d41d26b9ac6a03d7a12d41abfec6a8d26a481e0c1003c6c9fbc7cf6bd0b572ec2feb22c2eed900457532db98db3593a8e6267231b4886ac5ae4163dfaf8fec2a
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
