# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/functional
    REF boost-1.65.0
    SHA512 c8278d9774e072e98329ee746ba46abe7d1959f7821a8e16c341ea17bb5fc8be4b54c81d323d2179d63202afd62889bf9a4449b23c478bb794d3ebe4632fe47a
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
