# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/throw_exception
    REF boost-1.65.0
    SHA512 fa5e33aa9f1637c42de7658da15378c6744bc7f40f3476950a03dc45a71a01818e1f39e5c71b7df5ed553b01e11a141f31d05c2a931138fd89694c5d5825215f
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
