# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/smart_ptr
    REF boost-1.65.0
    SHA512 a37d5f43b1f821a02f99b0443f115642953a430e0d2aa9e7360bb765bcb43d1b59bbed00a0dbfdd1a63bea977157c8914a0045efd3deb901b04fb890121f0991
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
