# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/interval
    REF boost-1.65.0
    SHA512 ae1111e4fefb166e5d11ee19397054cb06e6027806484e6743de4f565c619a01c282a7ebdace44b5ac50b6553a1b8e1ec89b62def8695b977f5d0955058bc521
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
