# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/utility
    REF boost-1.65.0
    SHA512 937b38c01c762910b5b540fe5b3232681e197a0894011566ede20ba92333b08d278472f257fb4173d4e1e26aca4f20e3cbd7ae23531b4dd5ba7779de52ce1011
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
