# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/hana
    REF boost-1.65.0
    SHA512 69a08f4189353ff138995db24def5312a3df86fb477787266bce0b9c5424ba7043fdf0c5ab3266024b8f081bdd0e3fd659c0e45d2c34be768e3ea163ed9c6975
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
