# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/array
    REF boost-1.65.0
    SHA512 1680b2012e5068731b84d52e1297624898071f1fb8eed1dc1d7a3f787e960d84c556e30aad47c7dfb6871f773d41ad583fa8cb8c4408ec433bdb02006684aca8
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
