# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/uuid
    REF boost-1.65.0
    SHA512 89b8e51626778019f048e347a27c1ea131d74f20cadf56704a74fc34fc13b6d4b6cfc3cd69c34525596d78d7ebd2f24f5b30c7e36539f43477abc6c76b32fa0e
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
