# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/ratio
    REF boost-1.65.0
    SHA512 fa708addfe02f6f5ab0f9329a56c39b425c09d86efc621e24ae586967ca7428844202fba0f07a92135ee55c0ff24d053a07477621ab9771440c100c48a3203df
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
