# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/lexical_cast
    REF boost-1.65.0
    SHA512 e90897d5e419911f3991e896234df1b773563e929b4be7839984f250c968100bd3f0b3f39ac4aa2298ec5cc007cb0107acd407a4e1f7055bfaaa67bd659d0172
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
