# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/asio
    REF boost-1.65.0
    SHA512 2891f214769131538d8e78228bdacf72b5462ce959cd8f4c4c8409ff9e33a46685cf830151fa1c8e17540217cfb96ee49646fd37bfe7090a4a0a5635de3bd0f0
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
