# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/iterator
    REF boost-1.65.0
    SHA512 69794e73b0d812eeefcc992a7e7edcb23a6820f254a2a092263d96ec480b9c101f6e6568140b743bc95bb57614f7778af7ea32afdeeb37b451371c1f2d7f1e58
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
