# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/intrusive
    REF boost-1.65.0
    SHA512 e367e0e2bf7aee5fe18fdab95bac5be451addd04eecacc30d66e4b4117d2406b06029bc953f078fbc2396b2fa649701cdfd1e9629859997f4b908674c3f6f8f4
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
