# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/numeric_conversion
    REF boost-1.65.0
    SHA512 38af27aa09316005490cd45222d1a712785d3c8c36d83003200c4926b46fe3c94ceeaab53e932373dd51f637a3fa9e3b1d5574b1139b2eb1ce1d7115d7e8cc5c
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
