# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/any
    REF boost-1.65.0
    SHA512 f622113d0be257de7837af690c0081404c6056328b7cb5e0f5f8fd37710297819521888e6f2624d17574a2dabf23a0fd877c3e6d85962baa884152f9d92a41ea
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
