# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/scope_exit
    REF boost-1.65.0
    SHA512 7aba18c175a319e17c9c69e19b611b16798d203321d3a8a82251cefee1f57be1278459adcd207ee2a11d41a9bc8ad7f2ca3ff704e48cc2f2a7e54bb8ca33f036
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
