# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/multi_array
    REF boost-1.65.0
    SHA512 f962f43986cf598df0cd893f81437adb8c284213d0b077303a07379613249ae011e6f940796665a21d6f4ebc16a1fd2d5d996d0d5ad32f7ccb7f2ba688ad816e
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
