# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/move
    REF boost-1.65.0
    SHA512 8dc45b396063d924124b22f47ae294cb65fc862d510dac2f7f2b81c2be46c0b2a01d7c0bf5d88431a8e5737fbe5f11f913ec18fb360e4b12c0e069b095907704
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
