# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/crc
    REF boost-1.65.0
    SHA512 8dac8ccd85cbc3e82cca1ef221037b00ee76ba2d0f86d96c7a4c17bb2cf1504387a13561a3e067daba160cea421d8dfe7b1632f2d5afd8e7ab12230dcda371c9
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
