# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/format
    REF boost-1.65.0
    SHA512 43b2d69923988ceab1aac83bfa909425a59c077d8750bc569e0274e57ab5426aef7ecdcc6cf4936a259db7ddd0f98853de0e1bb49dc6e1e142aaab378fc143d9
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
