set CFG=%1
set FREETYPE_DIR=%2
set ADDITIONAL_LIB_DIR=%3
set PREFIX=%4
set PERL=%5
set NATIVE_PACKAGES_DIR=%6
set PLATFORM=%7

echo make-uwp: CFG=%CFG% FREETYPE_DIR=%FREETYPE_DIR% ADDITIONAL_LIB_DIR=%ADDITIONAL_LIB_DIR% PREFIX=%PREFIX% PERL=%PERL% PLATFORM=%PLATFORM%

call setVSvars.bat universal10.0%PLATFORM%

nmake -f Makefile.vc CFG=%CFG% FREETYPE=1 FREETYPE_DIR=%FREETYPE_DIR% ADDITIONAL_LIB_DIR=%ADDITIONAL_LIB_DIR% PREFIX=%PREFIX% PERL=%PERL%
nmake -f Makefile.vc CFG=%CFG% FREETYPE=1 FREETYPE_DIR=%FREETYPE_DIR% PREFIX=%NATIVE_PACKAGES_DIR% install






