# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/xpressive
    REF boost-1.65.0
    SHA512 96a8f4b496ce57781c04aac6e1321cea5773abc8140a71883b26d71476ea3c57b4e6d24bb1d26f7f7af4c86463d0e27aca902c7e18944fde2d26df414875c6ec
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
