# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/assign
    REF boost-1.65.0
    SHA512 ebf9664caa72a8e6f5f7d2100ee86c28d519794f7b74378dfb0acc5e0d9f011c125ceceda7d99e260999053cee129d345ee3e36d336bd9875aa6b183839172eb
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
