# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/range
    REF boost-1.65.0
    SHA512 8bf06e96db45054e0ad0949633ea5934390cf770b222da673a9d2616a86121990a67fe009f5a2f2857477a8c736a33513c00b05b799f25ffcf7772eeb98cf78b
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
