# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/fusion
    REF boost-1.65.0
    SHA512 b199ac278d9315cc234078d8559d0aa158aaab6b987c35e291d356172dfb6ff9191779299ef85323e55a5e9cdf61bf0c209df69b6b0d5fb445970076ef78580a
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
