# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/detail
    REF boost-1.65.0
    SHA512 e0eaa678f1e206223524ee9b59244fa6633dd8de63a90119db91ddfcac7337e8d6bf243f7dfd37af8e18dbe34ba23eb10ebd3f142f62c99e1f1837b06f299d8d
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
