# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/spirit
    REF boost-1.65.0
    SHA512 467f22d869bf1f48a2bc909e569aa3b369044a086ae04657b2d50b22ecc83077423c4e460feb56813b98b2e86205b3a6ab497fc1682036886323c1315ca1336d
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
