# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/lambda
    REF boost-1.65.0
    SHA512 6c627f4ea2a370ad16962b47fbb2304559610925be171a150c6501d4e24287d788c88bc9c33ef42870065614a2d2091200ef87bca0bc31f05cb2956ffdf8f614
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
