# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/logic
    REF boost-1.65.0
    SHA512 8fb9e24be6fad0b20cab72596506cdd4a09de8da0b437d6ef0685d32bb27275ea6febf890c6e74967c03801609c9c12d1583d78a06f6b4fb2ca1f92d832ad5bb
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
