# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/integer
    REF boost-1.65.0
    SHA512 90f07b1119ed0975046b7f560da3f11e21a86ec6d8f8a80f6a27b1e5c623b1939a4123fb675f3726c2739b340ebfe040b3b4fa2d4dd6fd52500d043902502565
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
