# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/poly_collection
    REF boost-1.65.0
    SHA512 84e2e1bd40f5066fdfd5281493cf8f56a4b2aa23916c025ee0126494bb4558481e9df0c42b696a477af2e538c4af5294519e90a6e5d8d8fba2638fcb61fe2478
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
