# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/winapi
    REF boost-1.65.0
    SHA512 393a69fb75c2db57846f45393a6a03c696a8eda0990b720837558c4a6239f0aaef59cc27fc751bb00a5c74bae3c77a486b617018ecec64fe039d95bcf6b5b04d
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
