# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/lockfree
    REF boost-1.65.0
    SHA512 b701eb0164b1fe2ffb01bb1e64718e4a1c56ed6ff95394544f2bf68b4eac6eb3694365a3248f8514ecd020cecc89b4d38d21ca869df01c471ded5f514f131d6a
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
