# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/gil
    REF boost-1.65.0
    SHA512 07974619e40f9e25bb097269d4eebf08bc7561193205506c361c6b6fdaf98e23f29d462bd0662b4498eafebd1bb9a25e193e24ab0e4d8d5d0853deb518649964
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
