# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/optional
    REF boost-1.65.0
    SHA512 d13444ad12bf9ddd3a25935eb6aa3b9475a180d2958b9221358ec861243707c7a9e26a0ba0a4a94c686c1daa6c428ab2a70f1c6ef3ac85140ade54c1f77d0106
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
