# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/bind
    REF boost-1.65.0
    SHA512 9522c130bbee7c3f228a03d9a6b61889978fe00b6d220dd863e4c050c437970f7a37f5f26d96418ee9d54ca16717585494ca28914fd3ab6b6baa0aa3a237605d
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
