# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/parameter
    REF boost-1.65.0
    SHA512 a8717733bc3bf0d23a1e4826ee68852e72a20c27e4a8d428e5b2d19a9308c6e698fb5c61ba4f91125433af171baf95a1ac16870c87230a43ffe358f36d44aae9
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
