# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/disjoint_sets
    REF boost-1.65.0
    SHA512 507781364ea424615d497579dfee9832c78dbe60dd6dad90e5e2a09a84784ce36cafd2038d613f14f6ba8502d30d6a8043f3183d135ba587cc246db05d30c4ea
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
