# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/dll
    REF boost-1.65.0
    SHA512 5dddc63da7f90805bdb66304e3d64428a7b19ee5336f0bbef42e15a5c5300c854557b7835ac773a07a74176659b92380002072fe78f524aeb808ca465038238a
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
