# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/rational
    REF boost-1.65.0
    SHA512 546292cf6bb8e5eb8c781d4f1f4564c304514cb889f91f085806af1ded00b72e01e9c73492eb48f3ca889b6a43e79a10d51dbaa81d6fdc75687548bb55bd27ad
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
