# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/static_assert
    REF boost-1.65.0
    SHA512 d5d6fe55cd908572336182571442d70362048b38bceb5947d61a2338f468593d8c903185677ec4b227c5b4aa37f5fa573b9510021b1d4460dd237b87ff89918c
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
