# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/endian
    REF boost-1.65.0
    SHA512 2ca387510c3a563d1f3d3c4e9a7846060a1deec6725c24f13e62e5ad83a0dfd86abfcc104bbab156e8b2d82269988690ccb2e4b275c762e8cbff8d3c19bf3505
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
