# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/conversion
    REF boost-1.65.0
    SHA512 eaa8ce6b78f1fa4fa9c6230dab61559643e24a7eded9f4cc4f797d15b466e705f3a8983a0d4f6ad42ada612b4b7a1c4b709d8b12489a47a83ec3c968e8326eb5
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
