# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/locale
    REF boost-1.65.0
    SHA512 b3de95b19578f7c731aac4cbfd60d889a5f28c78d77c101ee71e610918298927958f22c8358d50b2d8216948623a63bd0afb8ef51923ccdca6b799f4988051a1
    HEAD_REF master
)

if("icu" IN_LIST FEATURES)
    set(BOOST_LOCALE_ICU on)
else()
    set(BOOST_LOCALE_ICU off)
endif()

include(${CURRENT_INSTALLED_DIR}/share/boost-build/boost-modular-build.cmake)
boost_modular_build(
    SOURCE_PATH ${SOURCE_PATH}
    BOOST_CMAKE_FRAGMENT "${CMAKE_CURRENT_LIST_DIR}/cmake-fragment.cmake"
    OPTIONS
        boost.locale.iconv=off
        boost.locale.posix=off
        /boost/locale//boost_locale
        boost.locale.icu=${BOOST_LOCALE_ICU}
)
include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
