# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/assert
    REF boost-1.65.0
    SHA512 00a3b8ce30468141f0fc01967b5cc32e94ea24e9321262557cfaf926a60b6715aff6a13cd28cc3c91a1882fb2c6903b10d9aebabf5c45e8c29b30469eb39348f
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
