# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/multiprecision
    REF boost-1.65.0
    SHA512 a73de65bb5591a1d9e70e7f8afe5e74b38001976de17b52a322acefb26aa718a756bdcfe2edc091ce60ee9360357ad19ff367f357945cc295aeec3e74f8559c7
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
