# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/statechart
    REF boost-1.65.0
    SHA512 e912da4ee080af8c124cd8d8f09483aaca99219d4f7091983dc0189d215c6f9749ab9fd3b03b8d4d36c58c4f510121629cfc857ab35980b449b1668ca417a127
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
