# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/bimap
    REF boost-1.65.0
    SHA512 fc4675b3bab89ecf740dc62fb4d69bbe2a9c6d85969fa2972aff2727026ec67794ea6a55c214549faf8c597ff3677698dfa3b09130999ea9e0016ed9b5660319
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
