# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/compute
    REF boost-1.65.0
    SHA512 f1d9a0e6f78d7325c5aa9bfc19e4711563216cc796b2681853b124ffeead365b0a1921c5dd70a6bcaf1ca770d370ce1a83c109450a0a22e67c06694de03fdd2c
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
