# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/vmd
    REF boost-1.65.0
    SHA512 5c47a9f05ad9421c8738ec9b0534dafb840f9ad82a2502af594f076db5c2e4086977168982e1bd2323ef568491880dd6227e812490cf38aaa277105f4b442ad5
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
