# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/circular_buffer
    REF boost-1.65.0
    SHA512 eda48bfdcf984d39214e891b974140fd1b87e45de07fde145feb39d863e217457a9bb82a2bb936ab7853b6e03f07da115f9908c7607038d5215ad8a0694d0b09
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
