# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/accumulators
    REF boost-1.65.0
    SHA512 88821659d701999c513fbc2cfbe4ad0083bf6b5ed0c65d8ac99cfc49ff16f5a8f918e7ef8dd14611b69147159d41d6d5214995abefc688450e09b5bc644152fa
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
