# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/preprocessor
    REF boost-1.65.0
    SHA512 6ac5abdeaf8550211bb9db3ed7f33b10500be6bfc0d16f185608d059f00f9addeb1abda88463ae611c822648dffeaf78faa1e6cffdc625cda3d23c628c72b129
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
