# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/geometry
    REF boost-1.65.0
    SHA512 4ddac8a0e43c7c0d530ed2fd8c17aca725638f70b3ab20131c89ac65f6b93b7fbcf0d9a3563a3faf0966c4751053cc702e64de45918822e63c27e2a4409b6104
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
