# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/dynamic_bitset
    REF boost-1.65.0
    SHA512 6ef5c3dc36269613ff138c8653e2a5b70d83e57555363ed6eb3d7aff84fd70210ebe4ef4d02dc9e7e969f4214d4a7ab66d331f638d9eb0efbdcdbc218b6a0f18
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
