# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/tokenizer
    REF boost-1.65.0
    SHA512 2b17a65e977f43ee0a5806b05da865d1efc310da9325870a001f913bcf7c9a6b7fd3184dd4d934174a6a1794dd14a2d7af4cc85a239e8c364c6c907719d84d6b
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
