# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/process
    REF boost-1.65.0
    SHA512 c7cf048675c31290cf4bf3c7473a22a45ea1038cbbc676bc028834b0f4a5c435d52dada8a9918b0bccd3cf2765cc6a7734bb21e51f24744313bcf8cc07de356c
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
