# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/convert
    REF boost-1.65.0
    SHA512 9b8216c6a3af2a3dfaab020f336d257e0653bce5b17fededda72f312294b2fe75f1588dd9359d258ebcec7b83cfe32c389548b20c0dfc12a9e1a2057446b3ebc
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
