# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/typeof
    REF boost-1.65.0
    SHA512 b63441d94dcae051db370f248f37ada3163e105ca08d70449377fbf0e8e000e14cc6c14c90dbc15bf27772e9477bb008baee4a3fcab02e2c8be475ec80b13053
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
