# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/local_function
    REF boost-1.65.0
    SHA512 d097af6729e437dce0bd46b2922602b8afd2895f19b3160e2996a56fc96dc97c07cf24fcf7b45729e80ab5f6e3c695e27975a990a31ca43e81c288664c5d10a7
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
