# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/signals2
    REF boost-1.65.0
    SHA512 0cc35f9ed59afb9d91185e7d2e64250a41dd46a05e3ef4d795cdffab31276bd3abad80215751612864c54f9844eb540656598845c0244f61572907836e61dfe8
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
