# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/pool
    REF boost-1.65.0
    SHA512 6a865a413c57d77cae468847317df0fe4b4bcaa8f5ff68444a861fd21036a0f900d7d652f4e217ca81e9b719e567c706c31cf838693d82f2fb0ff4ff959b02a4
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
