# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/graph_parallel
    REF boost-1.65.0
    SHA512 3dc16e52c7be74bdd725b9f568b6a7fcfb534602568bef1677e15f35b1005d4d6a5132b30c999c52cffa982672d2be11709ebfacc60fe0cb7a37520558c7d734
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
