# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/core
    REF boost-1.65.0
    SHA512 f016dab1b478aeb34e3b425cacbab328b08f7cb53cccb55cfff695089041d7160cac553e9d0eaec9367ece3b2062767e5e9916450d75ece55a86345990062536
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
