# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/concept_check
    REF boost-1.65.0
    SHA512 e39cd9f5d3fbd6e2750f0465c8388f464cab9cd17dce902e5c2fb4c098735bc4b4a42f26bd9028b0f3e25d4ae86e0415b2d100e16b92bcb7496d0ab2310982cb
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
