# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/function_types
    REF boost-1.65.0
    SHA512 ae6ce7f7bba9a273a8d32676ad3c16b1638502fa12d103a982f446c28adce49e88e7a37b811b1157f1beb96347feb12d6cd0e4ee6d1242447315199a98a54ec0
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
