# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/algorithm
    REF boost-1.65.0
    SHA512 8177292ef7103bf147c0c449e39d9529609dea3cf1da276bed062550559e8c0bc48391137fe71484ae136ca5644bf083fd8f42be0035e15d8b03550549d245e2
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
