# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/mpl
    REF boost-1.65.0
    SHA512 a377eed6fd68c7f7a8735bfc399081ae876604bf6b67f388d7b289f46027bb1f2de6fbfebb87309665f21813ee449c1c48ac5fb0835095381e22a587dd134827
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
