# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/flyweight
    REF boost-1.65.0
    SHA512 0d2c7413c787e27dc8ee76367f222686290f8bc64b58d4f1a624809072987fd525c8f05b44a01de7983beed64721e182351d528cd9741cba0b30c32cabe8b6a5
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
