# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/property_tree
    REF boost-1.65.0
    SHA512 be46f5d8c3d8d2361bd3158d1487c7d29ec59551cc23a7ba87a010100a45b10b9a420dc142a92e6f1d787a38ed46bd1b77a6c47d5c48bbf667d7b3cbd791552b
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
