# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/metaparse
    REF boost-1.65.0
    SHA512 45d7ce4928582d79228d9f3373351a93735094cf2d0c625b29c9c98c7bdb47d7eed0a7d447f2f9726c1bb782c58c8b5a2aff0698f4aadcbf6cf374ba79d176b1
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
