# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/multi_index
    REF boost-1.65.0
    SHA512 efc360d7a4eeb9468aff2709188343e1c37404e2950f53eaf58dcd01198f5fc95c667463eca8b68fd3a0ff62c154b3f3cdc02d0df036fa83cd06591603166c13
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
