# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/property_map
    REF boost-1.65.0
    SHA512 893735b3ce1e033e7dcd8b72f0cf45433277d21b0942025a360017a1eea8f44a4865d29eee00f01796947cca19fc2ac3001c31e7c6b6d9671ad9d0c1926aa7f3
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
