# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/interprocess
    REF boost-1.65.0
    SHA512 859d0c1a209a61397b0924bdedb814610075b37edec6c0bbeb7fc3d0853f2a10bc5fb845ef426eac362afbdb6f247d90dc333f4af1b680c2098685c3c917d4f8
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
