# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/heap
    REF boost-1.65.0
    SHA512 f7b193c74e0556af64d092b258c9cdb85d5b5db4ed5b8f994cc53366e96afd1d1d662dd3208c0e18dc33806c166e2663fe1a9d24388b59d6b28cb2c9a1938810
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
