# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/unordered
    REF boost-1.65.0
    SHA512 d2dcdb33106fe06aadae0c13c8dcab84b12eef749375dc2346e2f7892950cb5115592699ef8139e0be312df3f13e0e5e9cfb7a61ef935bf31df90062be178d78
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
