# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/ptr_container
    REF boost-1.65.0
    SHA512 ea22d97d9faf1312980b27aa2f08c0818884e7fc060990e0bf78735024fe51f94c0eb7f8980c69a3ca4206d283188ef1e5931f70c28c6c84f047feabeede0d6d
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
