# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/sort
    REF boost-1.65.0
    SHA512 53ce11ab5bc54d980af99f56e2fa27275c164542dfaabfa2cf9c674d968f940b95ae3ba7a107daa65ab1289b306f523762e25b84082c2742ff7d54f0b441090f
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
